# render.yaml
services:
  - type: web
    name: stage-prod-platform
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "stage-prod-platform.onrender.com"
    healthCheckPath: /
    autoDeploy: true
    plans:
      - name: free
        disk:
          name: tiny
          mountPath: /opt/render/project/src
          sizeGB: 1